name = "redirectorator"
main = "src/worker.js"
compatibility_date = "2024-01-01"

triggers = [
  { pattern = "test.sukoneck.com/*", zone_name = "sukoneck.com" },
  { pattern = "test2.sukoneck.com/*", zone_name = "sukoneck.com" }
]

[observability.logs]
enabled = true
